---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wg-easy-creds
  namespace: wg-easy
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  encryptedData:
    password: AgA9N4zGKnxDGWryWuPMIn+zCV/Smi8pTnQo9LNkjCq0RrprQVlT4GJcu1xohh0utGyXKk18Uevxfx56/HWLk1knVo3NZf2W/uLKVGaxRdYHe0tPr4C/5XXHVo7uK99Z+SQ08AwrOedS2ifUT6PeOWTMj7FAmxmKd91Sm0GAz/GNwiMIh2MlHmMcMtd3HCZVAhkuTZGvLilQwJFxos+HpmMuS97neTXfNVNsbDMmROlW0uWVFjc7AzMVg4ZPB/JdP4ahJuBo3lUuRKHbU9W5pU+WzUvQ5D9cM+inoFtQ94ZGUqHvaGiODsXDY7nek5FGZYRNnoC5Hes3DFPCM4NzMss/vjYuo3Cahsx/mdRswRq03Bn2uSSJxy64cG0TXErwnnD8T0mYV8QYkIQNYNv2ASu2XLttwjGWn7GXklSLOT943vVV/6yLzh1kX6C8+WEvLDFSZf1oVFgEdwwOoHvXf/orUKEbBvQqCMtiNVI+Sn4yvLQabCmAsGQ/jOmHZ0npUGSLbMgAXMFtpEYYNOryaNJ8VUq+BmZB2HGfNgB7KfGYNvFXSZn8jAF+UGU2ti4JyNFDlzYNB41haqRq31nbyZQQoD8Gbh82hf+akdQGDbL6AZQXHX0S/rk5sWKW4Y9oXQ1gVTLcOz1YqHhd0jxo+l3EAnNWTliwkaIW+qLrmB1YlwnkR5bJ4+ZUKOD7y92xndhQOtIq7aOgVEWF3QgSWsQJ
    username: AgAjof0HCKOeEwS7j073Shw9vATh0fAEBO5FqEKIDJFwQde+jsjE2G5VB63Ulo1Y0qqGQtuUVn5ylN8DzON7naJ1wiREfTDlcRVWJPVu2q1HnC3jlngH4cnJnLUBJDmHxYn8vPpCkiIqUKRfNOPCEt9vjeeDZMYsVC/era4nxSlc3frVnczQqCLTXehBuG5TKO9D5vGtzwZPaWHkrg5XCHclHKDzhb1HrwaxzVsL95GumnFbOCHBCGR23R4KYswHtsS4E1m9CIMxK+8MASoN1AaxVUcxps6uH91pZoXOdQtJxRkMSu/TfpEL73kjY3lMN5Tye8qzGdVxqo4Eeye19cFsoot8X174Yi085bs+n0Ygt2bbVq0a7cxBmTqRiZOl06Pe+iukCk61/n42ivC+9Foi+p00Sc/qU6olmobmBZ69iaFbn1yL4uhYXOgGJE1CrgX4XGClY6mwOtc9d64gWQ/U1ExA/7p1afia734osGmPmZMYlSnL6J8DeZsIVQdMgB4PhHl5jybWx1LBYYf/oHU4qJVag+MvjGuHETTpb2zV5tyxbsyMD0rGrEVLBjDAs3HM2+YyRdKb6ORyWmo+WReaP2CVA3XvYbfDwXXtEyDySZ4CUYGLkba+Yjot//Iemtdys4OfOWM48WxwXJGtA7zGejJ3BFLbdkjbSkLuAIYi2m12Mi2gGlBR7HBYJaZXGXa9rCfIug==
  template:
    metadata:
      name: wg-easy-creds
      namespace: wg-easy
    type: Opaque
