---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wg-easy-password
  namespace: wg-easy
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  encryptedData:
    password: AgCiatmClY0PevVpvTNJEh9rVoVz82ygqhbTzzoAPkPczef9cUQ+NEorAWLihYsenQIvnPH3EpMx06dVtSC6JtyFnPjGWTE1AuFqsnRkEZUKV/nENgdkNHseU+ShqHIQgHotc8QpMzzVmI/YBfLDCAXY3l9GFCgmeX8zyS7I/6fMbGZnmMEl01g9D07PA9bnly4aRU9En+EnxEQ7ND5WwVcdpUbxBmE9AaFP58V3DTwqFHgoL17ZQnXr48R/kb/FRviaMvNboUgSpsdfA4Pw7HuUkEygicIZ4pmx0+oZ0bKdyeP3bu9G2LZPswpAh9ZT3MzW6EAmWRosCUvBzdFPtOnxBQM7waNbrPfrv5DrVhCXhV/4pxfwM7d0nKp1tcUw4I9GhOPQQ2ZCok4Tt3jDh7jvGbGl21y+PBIwwnJjSXcYA4tPNSnPbeKP869oBobaiXt9toXd8iHrDwmmz03MHlK2WzXu5Mgks7MVN3kzs3ZuZx1+G48nl5aZDcMepL7CPVKyVN6j2YMX5gyyPPQS5ZlH0DZCMS7csWxjuWuAHvUtzLQCY4OaOuv312rcTMChe0d4F9gLop9I4P812AtTsdJO+bUOGC253ivayQ+d/7BVlVFVcxjbceOmmBavM8vYF3TcPzb9+qIOa2qfIGycxSymOdTBLxqwaZtRD3h/SFChSCltH2QUOnUXPUfmjX8T+3H0GXpaFm9rqaizZu7sKo12
  template:
    metadata:
      name: wg-easy-password
      namespace: wg-easy
    type: Opaque
