apiVersion: v1
kind: Secret
metadata:
  name: rediscreds
  namespace: databases
  annotations:
    argocd.argoproj.io/sync-wave: '-1' # make sure it gets created before anything else
type: Opaque
stringData:
  password: "password"