apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cmd-params-cm
data:
  server.insecure: "true"
  kustomize.buildOptions: "--load-restrictor=LoadRestrictionsNone --enable-helm" # allow adding Helm-values outside the kustomize root directory + allow using helm