---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rediscreds
  namespace: databases
spec:
  encryptedData:
    password: AgCS4hHIXWP07VzeESgGq8Zr3jvg34G73xn6SqisPDvqdEBV8DHLRGkY2+OMw8j0gWlkpBCdUXHsZ8sXVjwZrZ1PeotDhcQJMHpgmfrDnDr+SZdFxm8NT1aAbd7udy1lAOQaLK04wu3iEapnh567gFuFa+DRLCM1UKEep3tX1zrt6uYDEwvw7zL/6bahGjUD+PNremkgWovTqlqCyjVwt/1xR0LNPh8dZ4BDD7S5NCyD7Vsj2VOoJ3fQZwqN1FgRY0Z312g/jy35BrfOTgax9gNWDmDMYHeKE50QT3HuC/yUIhE8nsLMtATVwd8x+UuOcrHsmu1xS4KjKvo9LaKgmRr+uR9MxcBohNPcLAiwQ56H72s4FoDNP0wndCFyoH4HySunkYrV2tKxZAbvlGKBBb1UOQn5Fg/ey5RBf2v7kTJGvO+SABpA9/Tnzqk5lH8OOx7XCt95WDFv+9cKuOD8vo7qdzq4LSLRU/orldjxxbiv1I8p9OPOj/08+xFtxZuOHC+QpSaPNmbp0um/3XFI8mG5UsYqNvcJrGq83Tc0UjqUFkc6xt/aemI1hQZImKCmkM+to/GO3w/fvOaLzmOwkvHyIp7+KGq8K3BRm0Pc0yGq+3SISd9lxlYowwA5OOvq3nkTmVjkLmWbo8sTk9ICazwKzIwUr5S7ticjC7RWUMl+OFNtSmZ7uiThUtmVNsD5zaX+cPs62NO1JEAwGdDrbbmXSXvbnJMxOWwyU4j66PICOnEZv2lXKrv5GucjgyLrEsUUF7PWkcATgYP89yVwmz7b
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: rediscreds
      namespace: databases
    type: Opaque
