---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rediscreds
  namespace: databases
spec:
  encryptedData:
    password: AgAGcOWxxp6cJYbJRKjYE3J0dr9XtiRSpq1UQ9wV/bA4MSci1N2jVMsdf9aPRj8ersYsibDlb1CtG0MTRVmOq3bM2SZUC/VkKgFeC/yGjnek+tk8iIKbF3hSfq3cp9vz+XfoRzQ/1nHZnNsGe2TjG+zECm7tOcYshRw+frcoULXITESNYXo+r4P9iXTTi87Cm9dfNptDLl0Ga2U32qSBITZThhHIb+ZktVa3lqTH1o97AXMFaccfyQ/cL/vdX5kBiHHZqwqqiHFIG9aGXKod4I2yJHsRZR7h6uUDb1GoHrUlVYdvHsyOBZpqUTs3pFRA4aHovXbmUye7XMQTlLV34l/zXHDpIX+lboS8sd3X4Q2JAvXs/xpSPXeF0bykSndkXFY+idUgIyYH3CPN3DqWmmqaiI22GvHylWk6txA2LgP4I/GiYc+bKExVKxjZLVDBSFrAIH5x4TWH4d45LYf0iuWvgh9kOFDkRebPScVdap9zMVh/LWldFSbzjvScaK4e5Voe2v2o8K6G8OswD3+9N31H+b2CZBH0skZHjeob8BfcRy07mkoUL70agzdZT+RXxkJkpSFHN/d9NiGlnSUYUNmFV11RZ5WbbR29/KGZG9NvnwSSTb9ISGgwbQtc3SLjU7r1RnkJSjvdftR/vM90WekDnaCwA8wzs3GQvkDRV6Ka9sW/EKaEDbJTBJ1G2EXhAnx4CAXu0TG/7+pbDRjp41lfUyyzxvqYa1jfBuBM/DcziE4u9wE6oOj+o1oVvagzNM63JIZQA2LWzHX1mTESwLOf
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: rediscreds
      namespace: databases
    type: Opaque
