global:
  defaultStorageClass: "longhorn"
  security:
    allowInsecureImages: true

image:
  repository: "redis"
  tag: "8.6"

architecture: standalone
clusterDomain: gport.giuliopime.dev

auth:
  existingSecret: "rediscreds"
  existingSecretPasswordKey: "password"

commonConfiguration: |-
  save "3600 1 300 100 60 10000"

master:
  resources:
    requests:
      cpu: 1
      memory: 2048Mi
    limits:
      cpu: 3
      memory: 4096Mi
  persistence:
    size: 30Gi
replica:
  replicaCount: 0
