---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: basic-auth
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgBItEcA40VUUlpi4u+9fE6Pk5npyuTVztknwSmXi00DLRu2w330YwP/M5F9t773ChKnqoPyGtKf7hMQJMZVlnJOXpmhgrSojoSvH3Pf3D5SxrLVoWHGpGKx2/ocisj9ckM6FnD4KCzapZT2vpGQu8sBs9sLma343cnpclbojKG9j7LLIPhZEaFfgH2SfqUhCMWSRjkXeNZbLkJixd6pj58zXjGOfQY9WDEQdzgMfxGMo57s9SIjge+6ToL9feSi4QZXm/fRl85MACZgaL60gDDQB2aTKA0Ni4OvL9xRMS/4T9tU4x7yDGAPKewxivRmib3c2x470xh3htSdX/I0UBYVOPP9QC7gLWEz90o/Oh/r2t5kxXYmNTdCDmHV5a2Lgi72Rgp2pk1w8aF2dkT2EBuMYl9i2E6euaBPxz3e2JF1HaSf5sopN1sG+UF5mEBqq56WZtHBu1pD6qZVmeoyKhC98FgHjjGQaVbrmRS76L+fXUOIPdyoWdFL8SD7bSyn0k7nvkyAuJbvhUJ+MtKFBUig+g9uomCGnRQ1Deg6gDRDruirz43U5t++ZwzTr/45gdyyIRyBYIEaGqMnoa1EXSRA65KpnFsweiuFpIUYn1ZkjwBJLhITWvrgKW6doJMaGEtBwfNulVgobvZboq5sT6SUYe2lYzOInfE51anF8vCW0JpFK+NpyXvaGCHk55L3cwU7aaq7OrXBgdo8YwWpOqj2fGCuvbjEvL9PW74aqPo61hMUCmFAaeLj93B9
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: basic-auth
      namespace: longhorn-system
    type: Opaque
