---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: basic-auth
  namespace: longhorn-system
spec:
  encryptedData:
    auth: AgBKuQsuzzPIBQJZlE72FtlyAgtVYcwBXbIOyPR4LTmNW4cqZFY2YTzmBSh2PZ83ra2FBR8c37YwiyvcelOFqqHoJEnZDwBQwfJd6lvV+B8M5YCqJrN8QVHzM0XtZkml6IphWRStlmHaCMv01k7OIleuNsBDqAAv6g1RQGgUpEt/FRqRZdWR9N+XEKa9guLCjhmrpM70PjhjSohR9I9vVDpbIZ0CDBrB6IZTTDZg683xryke8JTeRIKKhnACM9nsqCqHdTucsrwzCgMTuhYopfqLfxTfHT5viAKCeKRqyrLbzI2iqgX+RreCmoqqeXWdU6hyqV+9hVsK1ZxS44RM8SRupqY+8dHYHmWtfR4r3+txesqLCtZC3cAee5RCZeo451sI+f6knvJ34jv8sGCsRfYIXyz2HzZVn+va1liYXPILZCFSt26HPbTvPKaxNOnKjRrXyfKUlkfKlNP6oPiwxKRWk2s0RfBiYeJeC5Cusdjpg8khiJvPYKzAbfUFzXQfuofiUvaxcHTOMFVVuqTZaIW6akUycGpNwYh4mSTClfxZ16qr4bYhJ4lbv6LFPdNU0wfVOv2xTa+VTxf+wzU+GvRTT+he4SFkkitVrSJCYljXTuT5L6NsrPmfELb/1AsPuLzeaZcbWn3uX7vEXnLOdXKsomFWtgp9Jwp6lBV1Kj6yaVBTZY2cXo9pybqJUPvtlN/uqDqUFrG7d8tFj5nSAY6oFkraoNLQK2AC8LnkMtJomSPPThtmuckhp+Rc
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: basic-auth
      namespace: longhorn-system
    type: Opaque
