---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: '-1' # make sure it gets created before anything else
spec:
  encryptedData:
    admin-password: AgBnqR3yu4Yhp3aEC42HjZJI0aYU5BBzULPAwJe4uVbiKrO/ICW3soHfmaJh+/H6Y/vvkRqM3rPj1T3PILJuvSws1PEG9BWrLFVQvCG75wiUqMmX474sBRDfpOPDLPLihY9wnh7X/RfX/I00J2uPqoY5SPJOBbb8GLC1dTP3SHXpYd2+xJ3TOZxYzso2Wc39DCpsXl1WG8D69KeGL2qyA+3Eao8kewAZz/uZGWZBeBbh763pRJSQmBrsT8ern7x3RWR5sal9nVP8mVo5yCm28zJ3MH6deFyKeznBKJdGvhXRNH95kDtRRFFmaculuAtT5KqGKCgxqX4pUiCnlqoyHNmUflOw7gKiII1wDQaqhYfE+iXbPQ+SrTMTN0K76ohDAOgnKf/ZrZ+bfhTcnAfeXmnhv+4AdW/xpxHHD/WN3qpUsAAbA0CpFWfWsScmbV555qocHEquYUan4XMroXMMliPlbKiY1exjcVcus3ZDswjgufpgQ4nfelok+PlWIAlSxKuWzGytl3WlInOm3wTi3VilbWl/o4qNE6+YWd/hbb23Ovv5F9zxafwI+V4aaQgybFlJUCgCVRkGfPumxV5WoYMdAtYlUHMmVbRas4golw9bGwJPUtIVmUe7VlP4aYvrUShKfHL6ipmIBqZmMx4uTsWKHdyQicppGJZt+gdHRUCxXcpAJpmNzkerPnChp6/KBiYOBpEpHKJEYS88MLzPXIq3
    admin-user: AgAEtlEqQvc0u5XaT3w9Mj/iH8c/4y7gFr5bg6/oebobkqyY/S+LnX1bFwuNqMqIpPE2YPTh86Eoqjgv/MQ7WBH5W+mrXA18AEslr1v7ryyK36uwaO0I3Nt6F2VfivStLEJHQZaFXT2QJm/SxipEhVwsAC/U8VSSCR+2O1sWsATeM0J/yNjN6vTEWkrSINEEyMPcoMuSkIxa75/5clEPtfNoRtGesXZ3mz2vBWLQpBNBPbiVxw7VxEH7P8sCmcJTXRRDnBZx+thFKJhDnOdbdjuy0jaDxpC98fylo0DExwzIX0UsAXljPj6ks691wBTBx4Zswv2IJd0GWPtCQO8CT/+8V1LMWoDEqEiJFNX7QNsyV9HpHTljHpqOGw0cTpIMt1gshRdW5whDYVhFnNqFsRMI3UbTMuwd4pTpBhCqKfdJNKDODKVm3vKPupdwjzx1tW+IzIOaeBjzxMseO/YSqxzRXKGC5OdaD4ZNMeUPOj3VlXTGGuqxqP6T+WZGbzoG8XwgdvmpQGm0RVaaHeg6Jp6N1nSTMQlrOip12TaiRFXpGGVcKL6+x4ZT3xfp4p0VMe2uHnfmZLXPNIrL/LeDi7NvJ9ehGQkJ1AIXAlCHKjelU4+11GggLzpHnVX4ih7k8cBqWro1FIm+A/y4mOBxVIOvvOarVi3rqNr87eJCYZccT7wiNkDITh5vUqZc+WvL1sxd5drFpA==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: grafana-admin
      namespace: monitoring
    type: Opaque
