---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBRt2TGbgMjA37RkBw7M+6IMwpKRv2Idu1GZuFF0UYZJZTJ2LFe6UzT4F5bYEptSEnis75Pci9ZUuBgAxLM6My5EEse8VGZ9AeQc35HvjAahSqDgzjh82didiLIFYrX4mMOL2UJhw7CQX/RjXcGlLratcqCBMZM64dkEh08sxM9wy0j2HZQOZKlNNFWs//QxttfrwBNTedb5tpjP3mspPer6tu8qyoIhaPVhuaAbmIJ53rd7q0Kry67UTbvFdl/oV8KUUR/qxbd+DaWVA0Y1HPiQVyBBYGkapTseNQz8o89OB9I32z9GTBTDXT6zje/kArx7XC3TvGxrug/yEqwec+4ZRCB5hnftMI6ru9liqPJCSnGD+/0D4CccFkklfVuQ2wZGk01c/n9GEsZbyhcZhR+u8m+RjT+oOlmzGhBO98VNZr1nvucsbK1NvBIOHV4DdGUpVzHqVGO9gpLiLqBabhtZNBRiyMuIbi7oFdlAAAy8EqOhGjLaXoSLw+YImv1kRFaCI7BQvDMztjPQS0zfJgpeAdTHb1DxaYpwVSsB/Z3gBfkaAQTbFJYriKSTrmWUgxD2Etlnp8dfvjsT16FbY5uBOY1gtpkVPOW5UsNcaB9g2CRjYz4bEW4wyQdnnfVRAyjEEqddeUrr7WuYst0csrZ+/4Uto57Xajc/T/KUn9BhZs1ocfAhBmqNusTDfxc6bKKuaVwa/CCQJu53Oy89IJz
    admin-user: AgCBii/IkzhZ9p/R6bviBbLCZP4kzBm2y9TNw9ijm5XKCLC48HywG49CEscVabP0dgEfvDPLSuAKji7/tsbTygPWKv1mUQZ+aOy6sCVSW2b9s21DmiZ2DI7Vl/U7ZcNV7cgDp8+da5wSNh8I4kvWvapBYhD3dQk9fMrXdezLKcUOGe2VTgN3PxQqpw8bGMPnvzDWFOvGTXcgk2gJJkkE/y0VaVZtrj9XIxm6XBxNMpQv8r6JoGjB9NPiRn1Menai43ufVnAQAfRkUwaRIgqzRvuwN4PA2Z5f6eDROoQuBKKpapoJbza2w49+G9INfWEK8PYL/VdS0Xl/t53Fzcgh9xzBFPLsuuA3bCF0ZD6WJmrgN65dQvnrEDNKDWA2e/3Tp7TJRYGhiLGoD+Xi5HWL7r8cdLD3xi4w5eOV1iEk6S2Zgli9fHwucY0PpeU6UfxV4GM+UYa+yM88kqNX4WrgQH+4kWI5VJa/yeSdVqRtPzs4Ozmzfjz0CJjnQ9CLvB75XcTY/OtFGT5Cnj6pJMciRsggxv8RarUReDeCBJhXguX5PCU3IKUsHEwcPdrqIeeij5mdb+eRkm1zYWTdG/3oRKq7dZmkNHysOTH/6z4xK7TBWCmFMJQ786bttVHScAqk8JPzOjqe3ai4C2ohyOKznh9GuY0aNPxl+Hrg8L2/UIFL96eFPv4qJUApHqf2kA3eax6Ik/z3eg==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: grafana-admin
      namespace: monitoring
    type: Opaque
