apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gport
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Giuliopime/gport.git'
    targetRevision: main
    path: argocd/apps
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true