---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # make sure it gets created before anything else
spec:
  encryptedData:
    api-token: AgCJVxc0cFgpm8u3oKFCV0em0Jjdwzn0h0iPGXKBJxqmY9SSKKH4eFcwbRMNkxdm4T/UhfbaidNf4Re9gTbG5QcJGbCFz50zu8+vo6povSsapbtEMM1oBGNz47zqidGKypuGc7w2Ae1EeUkyrsd7g242ilO67rW2R649cLPI6HwP8Vu8ctNb5lyhP070cU2OGksA99DdWsubLYTypjvLNdO+hNXlz5Roz8pFFlF0yJMxBIjcrVr5GcKN/QemMlUj3ytNKVAhSbKFhesMGRoNxi7aL3R9zKqSUqyTxG729pBwIILCN442aILb7RY6H0Eh8Ko+h3VkgPo/wOWC+l18Fhmkj6KgsIrnia1jE/1cTBokbGJnauWqrh5cLyagQssLSxEGsYUTE890xzmhjrQX4K5EI8BrXi/yhgVmI/g1utg52T/I4RDOOq8aBvSflZxASW6VZwWG1rV/A3pMlfF2ouhPCGYRyIWDuQPmc6hGpLSF0Yk2odprX5M2sJRAkAqAdyF4py3n1byfOXdCvuAoDsgpv1G2VZ08ffhEcgqr61iLN4VKzpU/2Lj/arbIpNg398TTATLGxTV3NWlj09WxBGa8WzaZOPUwypJIHdZjyUrF3llvqNVshSdi63lwzaazPVPhrMVc6VIoM/hbfJ7Q2Kd+EztCvAn/Q0r32CqGbpTu9OA4ZdDQarr7tNyGfEjSmYiU9pEiV0//FHT5AJGs0AEvNYjfQSrub6YbZrnuR7k0MOcKSFML9rSJ
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
