---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCdiB3aCM2O2jmkXK8niMPP0Bj/ESwayALy4+nOH1FPUO8qJZkzRrccJ89qq5v/LBMqnXO2l8ZG7hir9qqTDV3sfw3BnRHnt4YNrV/eed+esATS7SQ45HqfY2cWj0zmdpTZg/b8xldhGXU11YFjieH6fBy/bBU+fh0ywRHmaxAFnmH38r/BADJ1hJMWPLkcLsZLfAkwVDyspIh5AxgPaOevcQE/GZ/rz/l6qBAJQ5t4NQX4uE6XqTc8djXwEKflnXYHZuQhsn8GGDz8wIU2bHkqKxIq+V8xM/DCGfq4qlV3sKPiHSJHOiHAmA1nruyYE9gz1sz1w5dPJNDXo9GGfSqZCnNdGdapDMnEoyU6mT11Dc+tqCK76SeLrGlTJN4do73fHShcJ7zm7J/7jKpqL81e/hNn5iF6pR8EOOlGp/spjmHk0nmejROtbGTgUhgVmk3x81XptRSnZK4KQtM/S61hjBuhEht7WTWPPj89tPPuf3Avnb8hlv/0eYppCMS/rELgar8Zqptp+/Up8ahwMIKOUREYbh0miYJ2lRIAS/rNW7hN07IzXDsk7wVDiKs2qrzUmfXhKLkyHQ25CbkgNPdO+BS137UEtgkc6dnxiuOzagLjgQ8Wi0tSNnBjVKC2bvTtymuDbjkqD2ZBCUAI94WHrwp3wzTmknxMFNIi4+MafDiDR7WbEIwf5qkwlTdxghTaHJidvrG9fxUH5FNbJU0ZCR/goI2fywyj1IQe3op7dEa5W2UPUMqs
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
