---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCJvthaGcAomVb9Zn04f29kuiRJjCYyjy5gcqoe7y2+/p79URsLiTn27g15xLixEkMuKuHUDpxWaYjbiNkOyTPyGBuqUmzXRdFBbJwgc3sBq0C7m0r7Uh6GK+UdgDGGVqzzNyNEyW4luaitQPnl/7v+U3YY3efM+u9vVgaYdv3uVAEIcnlfiu+FnDaoMMNC7HtslJ19IxihBknjAl59TYP0sbpy8Mv9feig19cTFq12E5A5Wn2K+7RxSWR4gT7GPhsJbnsE/bJqt2V8RYFP6Jbqy1iQfFeTURWXWtFzhXLaS6PGxm6QSl7/MbTrP3SsSbvLKl96NtnCPHVXsGSVLxytBW7QrsxoMV6Sl5EXTzhpUilqv4RtyNz7+RuEfeiRwfxITQEkK2uHKEP2i9X4ZelAp+gSe5sYou3SKy8oJ27m1po46htQlq0jWgUYr8LtZncUxvYmXBNFV4R/Xkr/0LslJowYqNmqsyAN27VggvBuj1rfL0RlYG+JzyWEJ2gmdx1a9s35KJyZOpDy/WPlT2vZFr6G7rdPbivDszSPhVczkPeZR/Gn7v4lXCxkwDHOsHCQkxFeJ379ionGjrqOayBEytQx+37UnF5IsTK3uRwH+W+svJLkDVyjBepHaSTuBcxRNAPvzQKhJLNKWyjy2/kcO/YfHqZGZlWcgCGiAR4Ae7R03u4m/4rkDjlipkBNU9LIYk8DSjmul2i1M6QOFuVu8T7zINe/BeGYMwS70JS07Dlwxa01BbBG
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
