apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-http
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ping@giuliopime.dev
    privateKeySecretRef:
      name: letsencrypt-prod-http
    solvers:
      - http01:
          ingress:
            class: nginx