apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: essentials
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: 'https://github.com/Giuliopime/gport.git'
    targetRevision: main
    path: k8s-resources/cert-manager