apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: 'https://github.com/Giuliopime/gport.git'
      targetRevision: main
      ref: gportrepo
      path: k8s-resources/kube-prometheus-stack
      directory:
        exclude: "secrets/*"
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      targetRevision: 77.9.1
      chart: kube-prometheus-stack
      helm:
        valueFiles:
          - $gportrepo/k8s-resources/kube-prometheus-stack/values.yaml