apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: essentials
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 77.9.1
    chart: kube-prometheus-stack
    helm:
      valueFiles:
        - ../../k8s-resources/kube-prometheus-stack/values.yaml