apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: essentials
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: databases
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 22.0.7
    chart: redis
    helm:
      valueFiles:
        - ../../k8s-resources/redis/values.yaml