apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wg-easy
  namespace: argocd
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: wg-easy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
  sources:
    - repoURL: 'https://github.com/Giuliopime/gport.git'
      targetRevision: main
      ref: gportrepo
      path: k8s-resources/wg-easy
      directory:
        exclude: "secrets/*"
    - repoURL: 'oci://ghcr.io/slybase/charts/wg-easy'
      targetRevision: 0.6.3
      chart: wgeasy
      helm:
        valueFiles:
          - $gportrepo/k8s-resources/wg-easy/values.yaml