apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: '-1' # make sure it gets created before anything else
type: Opaque
stringData:
  admin-user: "admin"
  admin-password: "password"